/*
Agility CMS REST API

Testing UrlRedirectionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package agilitycms

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	agilityClient "agility-fetch-go"
)

func Test_agilitycms_UrlRedirectionAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test UrlRedirectionAPIService UrlredirectionGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var guid string
		var apitype openapiclient.APIType

		resp, httpRes, err := apiClient.UrlRedirectionAPI.UrlredirectionGet(context.Background(), guid, apitype).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
