/*
Agility CMS REST API

Testing GalleryAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package agilitycms

import (
	agilityClient "agility-fetch-go"
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_agilitycms_GalleryAPIService(t *testing.T) {

	configuration := agilityClient.NewConfiguration()
	apiClient := agilityClient.NewAPIClient(configuration)

	t.Run("Test GalleryAPIService GalleryIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var guid string
		var apitype agilityClient.APIType
		var id int32

		resp, httpRes, err := apiClient.GalleryAPI.GalleryIdGet(context.Background(), guid, apitype, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
