/*
Agility CMS REST API

Testing PageAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package agilitycms

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	agilityClient "github.com/5PK/agility-fetch-go"
)

func Test_agilitycms_PageAPIService(t *testing.T) {

	configuration := agilityClient.NewConfiguration()
	apiClient := agilityClient.NewAPIClient(configuration)

	t.Run("Test PageAPIService PageChannelGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var guid string
		var apitype agilityClient.APIType
		var locale string
		var channel string

		resp, httpRes, err := apiClient.PageAPI.PageChannelGet(context.Background(), guid, apitype, locale, channel).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PageAPIService PageIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var guid string
		var apitype agilityClient.APIType
		var locale string
		var id int32

		resp, httpRes, err := apiClient.PageAPI.PageIdGet(context.Background(), guid, apitype, locale, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
