/*
Agility CMS REST API

Testing ListAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package agilitycms

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	agilityClient "github.com/5PK/agility-fetch-go"
)

func Test_agilitycms_ListAPIService(t *testing.T) {

	configuration := agilityClient.NewConfiguration()
	apiClient := agilityClient.NewAPIClient(configuration)

	t.Run("Test ListAPIService ListReferenceNameGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var guid string
		var apitype agilityClient.APIType
		var locale string
		var referenceName string

		resp, httpRes, err := apiClient.ListAPI.ListReferenceNameGet(context.Background(), guid, apitype, locale, referenceName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
