/*
Agility CMS REST API

Testing SitemapAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package agilitycms

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	agilityClient "agility-fetch-go"
)

func Test_agilitycms_SitemapAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SitemapAPIService SitemapFlatChannelNameGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var guid string
		var apitype openapiclient.APIType
		var locale string
		var channelName string

		resp, httpRes, err := apiClient.SitemapAPI.SitemapFlatChannelNameGet(context.Background(), guid, apitype, locale, channelName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SitemapAPIService SitemapNestedChannelNameGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var guid string
		var apitype openapiclient.APIType
		var locale string
		var channelName string

		resp, httpRes, err := apiClient.SitemapAPI.SitemapNestedChannelNameGet(context.Background(), guid, apitype, locale, channelName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
