/*
Agility CMS REST API

Testing ContentModelsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package agilitycms

import (
	agilityClient "agility-fetch-go"
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_agilitycms_ContentModelsAPIService(t *testing.T) {

	configuration := agilityClient.NewConfiguration()
	apiClient := agilityClient.NewAPIClient(configuration)

	t.Run("Test ContentModelsAPIService ContentmodelsGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var guid string
		var apitype agilityClient.APIType

		resp, httpRes, err := apiClient.ContentModelsAPI.ContentmodelsGet(context.Background(), guid, apitype).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
