/*
Agility CMS REST API

Agility CMS REST API for retrieving content from the Agility CMS.  The API Types are fetch (for published content) and preview (for latest, or staging content).

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agilitycms

import (
	"encoding/json"
)

// checks if the HeadlessContentSiteMapItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HeadlessContentSiteMapItem{}

// HeadlessContentSiteMapItem struct for HeadlessContentSiteMapItem
type HeadlessContentSiteMapItem struct {
	// ID of the page.
	PageID *int32 `json:"pageID,omitempty"`
	// Page name.
	Name NullableString `json:"name,omitempty"`
	// Path of the page.
	Path NullableString `json:"path,omitempty"`
	// Title of the page.
	Title NullableString `json:"title,omitempty"`
	// Menu text for the page.
	MenuText NullableString `json:"menuText,omitempty"`
	Visible *HeadlessContentPageVisibility `json:"visible,omitempty"`
	Redirect *RedirectUrl `json:"redirect,omitempty"`
	// Indicates if the item is a folder.
	IsFolder *bool `json:"isFolder,omitempty"`
	// Content ID of the item.
	ContentID NullableInt32 `json:"contentID,omitempty"`
}

// NewHeadlessContentSiteMapItem instantiates a new HeadlessContentSiteMapItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHeadlessContentSiteMapItem() *HeadlessContentSiteMapItem {
	this := HeadlessContentSiteMapItem{}
	return &this
}

// NewHeadlessContentSiteMapItemWithDefaults instantiates a new HeadlessContentSiteMapItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHeadlessContentSiteMapItemWithDefaults() *HeadlessContentSiteMapItem {
	this := HeadlessContentSiteMapItem{}
	return &this
}

// GetPageID returns the PageID field value if set, zero value otherwise.
func (o *HeadlessContentSiteMapItem) GetPageID() int32 {
	if o == nil || IsNil(o.PageID) {
		var ret int32
		return ret
	}
	return *o.PageID
}

// GetPageIDOk returns a tuple with the PageID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeadlessContentSiteMapItem) GetPageIDOk() (*int32, bool) {
	if o == nil || IsNil(o.PageID) {
		return nil, false
	}
	return o.PageID, true
}

// HasPageID returns a boolean if a field has been set.
func (o *HeadlessContentSiteMapItem) HasPageID() bool {
	if o != nil && !IsNil(o.PageID) {
		return true
	}

	return false
}

// SetPageID gets a reference to the given int32 and assigns it to the PageID field.
func (o *HeadlessContentSiteMapItem) SetPageID(v int32) {
	o.PageID = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HeadlessContentSiteMapItem) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HeadlessContentSiteMapItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *HeadlessContentSiteMapItem) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *HeadlessContentSiteMapItem) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *HeadlessContentSiteMapItem) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *HeadlessContentSiteMapItem) UnsetName() {
	o.Name.Unset()
}

// GetPath returns the Path field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HeadlessContentSiteMapItem) GetPath() string {
	if o == nil || IsNil(o.Path.Get()) {
		var ret string
		return ret
	}
	return *o.Path.Get()
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HeadlessContentSiteMapItem) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Path.Get(), o.Path.IsSet()
}

// HasPath returns a boolean if a field has been set.
func (o *HeadlessContentSiteMapItem) HasPath() bool {
	if o != nil && o.Path.IsSet() {
		return true
	}

	return false
}

// SetPath gets a reference to the given NullableString and assigns it to the Path field.
func (o *HeadlessContentSiteMapItem) SetPath(v string) {
	o.Path.Set(&v)
}
// SetPathNil sets the value for Path to be an explicit nil
func (o *HeadlessContentSiteMapItem) SetPathNil() {
	o.Path.Set(nil)
}

// UnsetPath ensures that no value is present for Path, not even an explicit nil
func (o *HeadlessContentSiteMapItem) UnsetPath() {
	o.Path.Unset()
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HeadlessContentSiteMapItem) GetTitle() string {
	if o == nil || IsNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HeadlessContentSiteMapItem) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *HeadlessContentSiteMapItem) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *HeadlessContentSiteMapItem) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *HeadlessContentSiteMapItem) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *HeadlessContentSiteMapItem) UnsetTitle() {
	o.Title.Unset()
}

// GetMenuText returns the MenuText field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HeadlessContentSiteMapItem) GetMenuText() string {
	if o == nil || IsNil(o.MenuText.Get()) {
		var ret string
		return ret
	}
	return *o.MenuText.Get()
}

// GetMenuTextOk returns a tuple with the MenuText field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HeadlessContentSiteMapItem) GetMenuTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MenuText.Get(), o.MenuText.IsSet()
}

// HasMenuText returns a boolean if a field has been set.
func (o *HeadlessContentSiteMapItem) HasMenuText() bool {
	if o != nil && o.MenuText.IsSet() {
		return true
	}

	return false
}

// SetMenuText gets a reference to the given NullableString and assigns it to the MenuText field.
func (o *HeadlessContentSiteMapItem) SetMenuText(v string) {
	o.MenuText.Set(&v)
}
// SetMenuTextNil sets the value for MenuText to be an explicit nil
func (o *HeadlessContentSiteMapItem) SetMenuTextNil() {
	o.MenuText.Set(nil)
}

// UnsetMenuText ensures that no value is present for MenuText, not even an explicit nil
func (o *HeadlessContentSiteMapItem) UnsetMenuText() {
	o.MenuText.Unset()
}

// GetVisible returns the Visible field value if set, zero value otherwise.
func (o *HeadlessContentSiteMapItem) GetVisible() HeadlessContentPageVisibility {
	if o == nil || IsNil(o.Visible) {
		var ret HeadlessContentPageVisibility
		return ret
	}
	return *o.Visible
}

// GetVisibleOk returns a tuple with the Visible field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeadlessContentSiteMapItem) GetVisibleOk() (*HeadlessContentPageVisibility, bool) {
	if o == nil || IsNil(o.Visible) {
		return nil, false
	}
	return o.Visible, true
}

// HasVisible returns a boolean if a field has been set.
func (o *HeadlessContentSiteMapItem) HasVisible() bool {
	if o != nil && !IsNil(o.Visible) {
		return true
	}

	return false
}

// SetVisible gets a reference to the given HeadlessContentPageVisibility and assigns it to the Visible field.
func (o *HeadlessContentSiteMapItem) SetVisible(v HeadlessContentPageVisibility) {
	o.Visible = &v
}

// GetRedirect returns the Redirect field value if set, zero value otherwise.
func (o *HeadlessContentSiteMapItem) GetRedirect() RedirectUrl {
	if o == nil || IsNil(o.Redirect) {
		var ret RedirectUrl
		return ret
	}
	return *o.Redirect
}

// GetRedirectOk returns a tuple with the Redirect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeadlessContentSiteMapItem) GetRedirectOk() (*RedirectUrl, bool) {
	if o == nil || IsNil(o.Redirect) {
		return nil, false
	}
	return o.Redirect, true
}

// HasRedirect returns a boolean if a field has been set.
func (o *HeadlessContentSiteMapItem) HasRedirect() bool {
	if o != nil && !IsNil(o.Redirect) {
		return true
	}

	return false
}

// SetRedirect gets a reference to the given RedirectUrl and assigns it to the Redirect field.
func (o *HeadlessContentSiteMapItem) SetRedirect(v RedirectUrl) {
	o.Redirect = &v
}

// GetIsFolder returns the IsFolder field value if set, zero value otherwise.
func (o *HeadlessContentSiteMapItem) GetIsFolder() bool {
	if o == nil || IsNil(o.IsFolder) {
		var ret bool
		return ret
	}
	return *o.IsFolder
}

// GetIsFolderOk returns a tuple with the IsFolder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeadlessContentSiteMapItem) GetIsFolderOk() (*bool, bool) {
	if o == nil || IsNil(o.IsFolder) {
		return nil, false
	}
	return o.IsFolder, true
}

// HasIsFolder returns a boolean if a field has been set.
func (o *HeadlessContentSiteMapItem) HasIsFolder() bool {
	if o != nil && !IsNil(o.IsFolder) {
		return true
	}

	return false
}

// SetIsFolder gets a reference to the given bool and assigns it to the IsFolder field.
func (o *HeadlessContentSiteMapItem) SetIsFolder(v bool) {
	o.IsFolder = &v
}

// GetContentID returns the ContentID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HeadlessContentSiteMapItem) GetContentID() int32 {
	if o == nil || IsNil(o.ContentID.Get()) {
		var ret int32
		return ret
	}
	return *o.ContentID.Get()
}

// GetContentIDOk returns a tuple with the ContentID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HeadlessContentSiteMapItem) GetContentIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContentID.Get(), o.ContentID.IsSet()
}

// HasContentID returns a boolean if a field has been set.
func (o *HeadlessContentSiteMapItem) HasContentID() bool {
	if o != nil && o.ContentID.IsSet() {
		return true
	}

	return false
}

// SetContentID gets a reference to the given NullableInt32 and assigns it to the ContentID field.
func (o *HeadlessContentSiteMapItem) SetContentID(v int32) {
	o.ContentID.Set(&v)
}
// SetContentIDNil sets the value for ContentID to be an explicit nil
func (o *HeadlessContentSiteMapItem) SetContentIDNil() {
	o.ContentID.Set(nil)
}

// UnsetContentID ensures that no value is present for ContentID, not even an explicit nil
func (o *HeadlessContentSiteMapItem) UnsetContentID() {
	o.ContentID.Unset()
}

func (o HeadlessContentSiteMapItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HeadlessContentSiteMapItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PageID) {
		toSerialize["pageID"] = o.PageID
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Path.IsSet() {
		toSerialize["path"] = o.Path.Get()
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if o.MenuText.IsSet() {
		toSerialize["menuText"] = o.MenuText.Get()
	}
	if !IsNil(o.Visible) {
		toSerialize["visible"] = o.Visible
	}
	if !IsNil(o.Redirect) {
		toSerialize["redirect"] = o.Redirect
	}
	if !IsNil(o.IsFolder) {
		toSerialize["isFolder"] = o.IsFolder
	}
	if o.ContentID.IsSet() {
		toSerialize["contentID"] = o.ContentID.Get()
	}
	return toSerialize, nil
}

type NullableHeadlessContentSiteMapItem struct {
	value *HeadlessContentSiteMapItem
	isSet bool
}

func (v NullableHeadlessContentSiteMapItem) Get() *HeadlessContentSiteMapItem {
	return v.value
}

func (v *NullableHeadlessContentSiteMapItem) Set(val *HeadlessContentSiteMapItem) {
	v.value = val
	v.isSet = true
}

func (v NullableHeadlessContentSiteMapItem) IsSet() bool {
	return v.isSet
}

func (v *NullableHeadlessContentSiteMapItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHeadlessContentSiteMapItem(val *HeadlessContentSiteMapItem) *NullableHeadlessContentSiteMapItem {
	return &NullableHeadlessContentSiteMapItem{value: val, isSet: true}
}

func (v NullableHeadlessContentSiteMapItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHeadlessContentSiteMapItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


